version: '3'
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - main
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      yt_api_key_1: ${yt_api_key_1}
      yt_api_key_2: ${yt_api_key_2}
      yt_api_key_3: ${yt_api_key_3}
      FLASK_APP: app.py
      FLASK_ENV: production
      DATABASE_URL: postgresql://user:password@postgres:5432/postgres
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - main
    volumes:
      - .:/app

  redis:
    image: redis:latest
    networks:
      - main

volumes:
  postgres-data:

networks:
  main:
