version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5001"
    environment:
      yt_api_key_1: ${yt_api_key_1}
      yt_api_key_2: ${yt_api_key_2}
      yt_api_key_3: ${yt_api_key_3}
      FLASK_APP: app.py
      FLASK_ENV: production
      DATABASE_URL: postgresql://user:password@postgres:5432/database_name
    depends_on:
      - postgres
      - redis
    command: gunicorn --workers 3 --bind 0.0.0.0:5001 app:app --log-level=debug --access-logfile - --error-logfile -
    restart: always

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database_name
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest

volumes:
  postgres-data: